import type { ComplianceControl } from "./governance-data";

export const complianceControls: ComplianceControl[] = [
  { id: "CTRL-VULN-001", name: "Vulnerability Scanning", category: "Security Compliance", status: "Active", riskLevel: "High", owner: "Security Team", lastChecked: "2026-07-13", nextReview: "2026-08-13", complianceStandard: "ISO 27001 / NIST CSF", description: "Ensures platform services, API endpoints, and industrial integrations are scanned for known vulnerabilities.", evidence: "Last scan found 2 medium issues and 0 critical issues.", recommendedAction: "Patch dependencies and rerun scan before production deployment.", relatedModules: ["Security Operations", "API Security", "Audit Log"] },
  { id: "CTRL-ACCESS-002", name: "Access Control Review", category: "Access Governance", status: "Active", riskLevel: "High", owner: "Security Team", lastChecked: "2026-07-12", nextReview: "2026-10-12", complianceStandard: "ISO 27001", description: "Validates role assignments and least-privilege access to governed industrial data.", evidence: "Quarterly review completed; 3 stale assignments require removal.", recommendedAction: "Remove stale assignments and document manager approval.", relatedModules: ["Roles", "Audit Log"] },
  { id: "CTRL-RET-003", name: "Data Retention Review", category: "Data Governance", status: "Review Required", riskLevel: "High", owner: "Governance Team", lastChecked: "2026-07-10", nextReview: "2026-07-24", complianceStandard: "PIPEDA / Internal Policy", description: "Confirms each dataset has an approved and current retention lifecycle.", evidence: "Two datasets exceed their approved retention thresholds.", recommendedAction: "Assign current policies and remediate expired records.", relatedModules: ["Data Governance", "Audit Log"] },
  { id: "CTRL-ENC-004", name: "Encryption Verification", category: "Security Compliance", status: "Active", riskLevel: "Critical", owner: "Security Team", lastChecked: "2026-07-13", nextReview: "2026-08-13", complianceStandard: "SOC 2 / ISO 27001", description: "Verifies encryption at rest and in transit for restricted data.", evidence: "All production stores use approved encryption; one test connector needs TLS renewal.", recommendedAction: "Renew the test connector certificate.", relatedModules: ["Security Operations", "Data Input"] },
  { id: "CTRL-MFA-005", name: "MFA Enforcement", category: "Access Governance", status: "Active", riskLevel: "Critical", owner: "Security Team", lastChecked: "2026-07-13", nextReview: "2026-08-13", complianceStandard: "NIST CSF", description: "Ensures privileged and administrative users authenticate with MFA.", evidence: "100% of active privileged accounts are enrolled.", recommendedAction: "Continue monthly enrollment monitoring.", relatedModules: ["Users", "Roles"] },
  { id: "CTRL-API-006", name: "API Key Rotation", category: "API Security", status: "Monitoring", riskLevel: "High", owner: "Security Team", lastChecked: "2026-07-11", nextReview: "2026-08-01", complianceStandard: "SOC 2", description: "Checks API credentials against approved age and rotation limits.", evidence: "One production key expires within 21 days.", recommendedAction: "Rotate the expiring production credential.", relatedModules: ["API Security", "Audit Log"] },
  { id: "CTRL-AUD-007", name: "Audit Log Review", category: "Audit Assurance", status: "Active", riskLevel: "Medium", owner: "Compliance Team", lastChecked: "2026-07-13", nextReview: "2026-08-13", complianceStandard: "SOC 2 / ISO 27001", description: "Reviews audit completeness, integrity, and anomalous administrative activity.", evidence: "No gaps detected across sampled governance events.", recommendedAction: "Retain evidence with the monthly compliance package.", relatedModules: ["Audit Log", "Activity"] },
  { id: "CTRL-IR-008", name: "Incident Response Review", category: "Security Compliance", status: "Monitoring", riskLevel: "High", owner: "Security Team", lastChecked: "2026-07-09", nextReview: "2026-08-09", complianceStandard: "NIST CSF", description: "Validates incident response ownership, escalation paths, and evidence.", evidence: "Tabletop exercise passed with one communication delay.", recommendedAction: "Update the escalation contact tree.", relatedModules: ["Security Operations", "Notifications"] },
  { id: "CTRL-BKP-009", name: "Backup Verification", category: "Operational Resilience", status: "Active", riskLevel: "Critical", owner: "Operations Team", lastChecked: "2026-07-13", nextReview: "2026-07-20", complianceStandard: "ISO 27001", description: "Verifies backups can be restored within approved recovery objectives.", evidence: "Latest restore test completed in 42 minutes.", recommendedAction: "Continue weekly restore verification.", relatedModules: ["Operations", "Audit Log"] },
  { id: "CTRL-POL-010", name: "Policy Compliance Review", category: "Data Governance", status: "Review Required", riskLevel: "Medium", owner: "Governance Team", lastChecked: "2026-07-08", nextReview: "2026-07-22", complianceStandard: "Internal Policy / PIPEDA", description: "Confirms policy assignments, approvals, and review dates remain current.", evidence: "One draft policy has been awaiting approval for 45 days.", recommendedAction: "Route the draft policy to its designated approver.", relatedModules: ["Data Governance", "Activity"] },
];
